apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{.Release.Name}}-secrets
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    OPENAI_API_KEY: AgA31h7KMS5mUmgeB5COrey73G9aGbrQlWCpiJipM8kLVkYlIAogS3WP6niiGnOhjUJtEn0IXMBlCmcxkAPBy+iLaBbItt32Tp3SQE31+1WFbbqhZYxoOGekYy8SdCutabQwG+m3oZbiaEyZMglQkWce/6HrRZZnfVBNeK1CebP267BGxeVYkhmJH///uhjMe6B81adMJV7Hh7c3SIbDw4YtTeeJnv+cj3zPLsrJmWFNmMui9N0MY40/58v6381SAq2ZxC1496uXKJm3gVj0UT6Xz363Bg6U1wEIAotl9IwPQdJxWO1NxQewLeG6ub/19pJX2/ufyx2oAF2bCOpukpN///yFKgceCzz+cc/Yj0F4dDIK1rDlDN6aRAgfzyANkRyB88HgtsQ8m0oMli/5RatqDPJNjgQyjAv6oAwwTrkyGKqzEaF0d5jD0rW4ICgrS1f8ZLRt+6k6ZNcGtWZL9Q41vcbyz1qsNSN9D9ji/77rwOfBaCUEtiC1nyrcX61OgFJg77z1s4RM0FApR6qUCOwqLinMb0ioo1iYIdHFNM9mrFjRYX8P5LdKH7h39adX5Idf2xPSKsX6uzkFQhYh5HKmhDm3UWfEL8ufSORrhTkZMPfiB012uMWZLJjkl6xMlxi3U1X3fmjJpSUZcjBjj56jHZj5ET+nQSEpu1hDWqdwOj3wofMY6o1ZRQV5ClT2G4yDjwln5iUhrDc67tJwEeXvYh8nwZWH5HqtD1NafhG4U4WuBcurJUpWlutW3kWS44Gfpzjipsisp/EBu4zHt8ygb/M+O9+PQsKuYB2xFmgxlVrXfJ4Gm6krXtgpk7zWVny7DeakAyeeLs3+lSh7hMr11HsytYEIe/f3CD7tn7lwwY0FJLnuB+/z/NRyjmZwD1gJ6GFcnVNiNpWFgNTexzzMthZEVQ==
  template:
    metadata:
      name: {{.Release.Name}}-secrets
      namespace: default
    type: Opaque
